name = "PorousConvection"
uuid = "ad09bf41-3a10-4e70-9460-3aba29432f73"
authors = ["youwuyou <youwuyou@student.ethz.ch> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
